version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
            
  cfn-deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/assume_role_with_web_identity:
          role_arn: $AWS_OIDC_ROLE_ARN
      - run: 
          name: run cfn-deploy
          command: aws cloudformation deploy --template-file ./cloudformation/*.yml
workflows:
  cfn-lint:
    jobs:
      - cfn-lint
  cfn-deploy:
    jobs:
      - cfn-deploy
