version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:         
  clfstack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/assume_role_with_web_identity:
          role_arn: $AWS_ARN
      - run: 
          name: Deploy cfn
          command: aws cloudformation deploy --template-file ./cloudformation/network.yml --stack-name network  --no-fail-on-empty-changeset --region ap-northeast-1

workflows:
  lint_deploy_test:
    jobs:
      - clfstack:
          filters:
            branches:
              only:
                - main