version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  cfn-deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: 
          name: run cfn-deploy
          command: aws cloudformation deploy --template-file ./cloudformation/network.yml --stack-name network
#          command: aws cloudformation deploy --template-file ./cloudformation/security.yml --stack-name security
#          command: aws cloudformation deploy --template-file ./cloudformation/app.yml --stack-name app

workflows:
  version: 2
  cfn-lint:
    jobs:
      - cfn-lint
  cfn-deploy:
    jobs:
      - cfn-deploy
