version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

orbs:
  aws-cli: circleci/aws-cli@5.1
jobs:
  appstack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/assume_role_with_web_identity:
          role_arn: $AWS_OIDC_ROLE_ARN
      - run: 
          name: Deploy VPC
          command: aws cloudformation deploy --template-file ./cloudformation/app.yml --stack-name app  --no-fail-on-empty-changeset --region ap-northeast-1

workflows:
  cfn-lint:
    jobs:
      - cfn-lint
  cfn-deploy:
    jobs:
      - appstack
