  deploy:
    steps:
      - run:
          name: deploy
          command: |
            set -x

          aws --version

            echo "any deploy command"

            aws s3 ls

jobs:
  lint_and_unit_test:
    executor: deploy_container
    steps:
      - checkout
      - lint_and_unit_test

  deploy:
    executor: deploy_container
    steps:
      - checkout
      - aws-cli/install
      - deploy

workflows:
  version: 2
  release-workflow:
    jobs:
      - lint_and_unit_test: