version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  build: 
    executor: ansible-playbook/default
    steps:
      - checkout
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
#          private-key: <<parameters.private-key>>

workflows:
  version: 2
  ansibledeploy:
    jobs:
      - build